#!/bin/bash

# Define the virtual environment directory
VENV_DIR=".venv"

# Check if the virtual environment directory exists
if [ ! -d "$VENV_DIR" ]; then
  echo "Virtual environment not found. Creating one..."
  python3 -m venv $VENV_DIR
  source $VENV_DIR/bin/activate
  echo "Installing requirements..."
  pip install -r requirements.txt
else
  source $VENV_DIR/bin/activate
fi

# Run the password.py script
python .tool/password/password.py "$@"
